// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

// Protobuf Java Version: 3.25.2
package io.grpc.examples.helloworld;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MixRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MixRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MixRequest_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MixRequest_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_MixRequest_Abcd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_MixRequest_Abcd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"\276\005\n\nMixRe" +
      "quest\022\024\n\014double_field\030\001 \001(\001\022\023\n\013float_fie" +
      "ld\030\002 \001(\002\022\023\n\013int32_field\030\003 \001(\005\022\023\n\013int64_f" +
      "ield\030\004 \001(\003\022\024\n\014uint32_field\030\005 \001(\r\022\024\n\014uint" +
      "64_field\030\006 \001(\004\022\024\n\014sint32_field\030\007 \001(\021\022\024\n\014" +
      "sint64_field\030\010 \001(\022\022\025\n\rfixed32_field\030\t \001(" +
      "\007\022\025\n\rfixed64_field\030\n \001(\006\022\026\n\016sfixed32_fie" +
      "ld\030\013 \001(\017\022\026\n\016sfixed64_field\030\014 \001(\020\022\022\n\nbool" +
      "_field\030\r \001(\010\022\024\n\014string_field\030\016 \001(\t\022-\n\006st" +
      "atus\030\020 \001(\0162\035.helloworld.MixRequest.Statu" +
      "s\0228\n\020shipping_address\030\021 \001(\0132\036.helloworld" +
      ".MixRequest.Address\022)\n\004abcd\030\022 \001(\0132\033.hell" +
      "oworld.MixRequest.Abcd\022\026\n\016repeated_field" +
      "\030\023 \003(\t\022 \n\024repeated_int32_field\030\024 \003(\005B\002\020\001" +
      "\0329\n\007Address\022\016\n\006street\030\001 \001(\t\022\014\n\004city\030\002 \001(" +
      "\t\022\020\n\010zip_code\030\003 \001(\t\0322\n\004Abcd\022\t\n\001a\030\001 \001(\t\022\t" +
      "\n\001b\030\002 \001(\t\022\t\n\001c\030\003 \001(\t\022\t\n\001d\030\004 \001(\t\">\n\006Statu" +
      "s\022\013\n\007UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\017\n\013IN_PROGRE" +
      "SS\020\002\022\t\n\005ERROR\020\003\"\035\n\nHelloReply\022\017\n\007message" +
      "\030\001 \001(\t2E\n\007Greeter\022:\n\006SayMix\022\026.helloworld" +
      ".MixRequest\032\026.helloworld.HelloReply\"\000B6\n" +
      "\033io.grpc.examples.helloworldB\017HelloWorld" +
      "ProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_MixRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_MixRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MixRequest_descriptor,
        new java.lang.String[] { "DoubleField", "FloatField", "Int32Field", "Int64Field", "Uint32Field", "Uint64Field", "Sint32Field", "Sint64Field", "Fixed32Field", "Fixed64Field", "Sfixed32Field", "Sfixed64Field", "BoolField", "StringField", "Status", "ShippingAddress", "Abcd", "RepeatedField", "RepeatedInt32Field", });
    internal_static_helloworld_MixRequest_Address_descriptor =
      internal_static_helloworld_MixRequest_descriptor.getNestedTypes().get(0);
    internal_static_helloworld_MixRequest_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MixRequest_Address_descriptor,
        new java.lang.String[] { "Street", "City", "ZipCode", });
    internal_static_helloworld_MixRequest_Abcd_descriptor =
      internal_static_helloworld_MixRequest_descriptor.getNestedTypes().get(1);
    internal_static_helloworld_MixRequest_Abcd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_MixRequest_Abcd_descriptor,
        new java.lang.String[] { "A", "B", "C", "D", });
    internal_static_helloworld_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
